import uuid


class AirTablePost:
    def __init__(
        self,
        _id: str = None,
        air_table_id: str = None,
        name: str = None,
        images: dict = None,
        status: list = None,
        us_web_lauch_date: str = None,
        social_date_1: str = None,
        social_date_2: str = None,
        social_date_3: str = None,
        social_date_4: str = None,
        social_date_5: str = None,
        social_date_6: str = None,
        social_date_7: str = None,
        social_date_8: str = None,
        social_channel: list = None,
        content_author: list = None,
        social_campaign: list = None,
        live_urls: str = None,
        satus_update: str = None,
        tweet_copy: str = None,
        paid_copy: str = None,
        linkedin_facebook_copy: str = None,
        article_copy: list = None,
        us_web_compliance_log_number: str = None,
        programs_and_themes: str = None,
        web_role: list = None,
        web_date_of_last_use: str = None,
        email_trigger: bool = None,
        linkedin_thought_leader: list = None,
        editorial_rep: list = None,
        social_team: list = None,
        web_topic_tag: str = None,
        ca_web_launch: str = None,
        planning: list = None,
        where_to_post: list = None,
        editorial_process_steps: list = None,
        ca_web_compliance_log: str = None,
        see_associated_record: list = None,
        social_brand: list = None,
        soocial_review_queue: str = None,
        ca_web_fr_translation_publish_date: str = None,
        link_to_qqq_images: list = None,
        social_canada_copy: str = None,
        qqq_content_partner: str = None,
        instagram_copy: str = None,
        social_initiative: str = None,
    ) -> None:
        self._id = _id
        self.air_table_id = air_table_id
        self.name = name
        self.images = images
        self.status = status
        self.us_web_lauch_date = us_web_lauch_date
        self.social_date_1 = social_date_1
        self.social_date_2 = social_date_2
        self.social_date_3 = social_date_3
        self.social_date_4 = social_date_4
        self.social_date_5 = social_date_5
        self.social_date_6 = social_date_6
        self.social_date_7 = social_date_7
        self.social_date_8 = social_date_8
        self.social_channel = social_channel
        self.content_author = content_author
        self.social_campaign = social_campaign
        self.live_urls = live_urls
        self.satus_update = satus_update
        self.tweet_copy = tweet_copy
        self.paid_copy = paid_copy
        self.linkedin_facebook_copy = linkedin_facebook_copy
        self.article_copy = article_copy
        self.us_web_compliance_log_number = us_web_compliance_log_number
        self.programs_and_themes = programs_and_themes
        self.web_role = web_role
        self.web_date_of_last_use = web_date_of_last_use
        self.email_trigger = email_trigger
        self.linkedin_thought_leader = linkedin_thought_leader
        self.editorial_rep = editorial_rep
        self.social_team = social_team
        self.web_topic_tag = web_topic_tag
        self.ca_web_launch = ca_web_launch
        self.planning = planning
        self.where_to_post = where_to_post
        self.editorial_process_steps = editorial_process_steps
        self.ca_web_compliance_log = ca_web_compliance_log
        self.see_associated_record = see_associated_record
        self.social_brand = social_brand
        self.soocial_review_queue = soocial_review_queue
        self.ca_web_fr_translation_publish_date = ca_web_fr_translation_publish_date
        self.link_to_qqq_images = link_to_qqq_images
        self.social_canada_copy = social_canada_copy
        self.qqq_content_partner = qqq_content_partner
        self.instagram_copy = instagram_copy
        self.social_initiative = social_initiative
